//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS24
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид поддержки.
    /// </summary>
    // *** Start programmer edit section *** (ВидПоддержки CustomAttributes)

    // *** End programmer edit section *** (ВидПоддержки CustomAttributes)
    [AutoAltered()]
    [Caption("Вид поддержки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидПоддержкиE", new string[] {
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'"})]
    [AssociatedDetailViewAttribute("ВидПоддержкиE", "СписокФорм", "СписокФормE", true, "", "Список форм", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ВидПоддержкиE", "СписокУсловий", "СписокУсловийE", true, "", "Список условий", true, new string[] {
            ""})]
    [View("ВидПоддержкиL", new string[] {
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'"})]
    public class ВидПоддержки : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fОписание;
        
        private IIS.ISS24.DetailArrayOfСписокУсловий fСписокУсловий;
        
        private IIS.ISS24.DetailArrayOfСписокФорм fСписокФорм;
        
        // *** Start programmer edit section *** (ВидПоддержки CustomMembers)

        // *** End programmer edit section *** (ВидПоддержки CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Наименование CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Get start)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Get end)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Set start)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Set end)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Описание CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Описание Get start)

                // *** End programmer edit section *** (ВидПоддержки.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (ВидПоддержки.Описание Get end)

                // *** End programmer edit section *** (ВидПоддержки.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Описание Set start)

                // *** End programmer edit section *** (ВидПоддержки.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (ВидПоддержки.Описание Set end)

                // *** End programmer edit section *** (ВидПоддержки.Описание Set end)
            }
        }
        
        /// <summary>
        /// Вид поддержки.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.СписокУсловий CustomAttributes)
        public virtual IIS.ISS24.DetailArrayOfСписокУсловий СписокУсловий
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий Get start)

                // *** End programmer edit section *** (ВидПоддержки.СписокУсловий Get start)
                if ((this.fСписокУсловий == null))
                {
                    this.fСписокУсловий = new IIS.ISS24.DetailArrayOfСписокУсловий(this);
                }
                IIS.ISS24.DetailArrayOfСписокУсловий result = this.fСписокУсловий;
                // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий Get end)

                // *** End programmer edit section *** (ВидПоддержки.СписокУсловий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий Set start)

                // *** End programmer edit section *** (ВидПоддержки.СписокУсловий Set start)
                this.fСписокУсловий = value;
                // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий Set end)

                // *** End programmer edit section *** (ВидПоддержки.СписокУсловий Set end)
            }
        }
        
        /// <summary>
        /// Вид поддержки.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.СписокФорм CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.СписокФорм CustomAttributes)
        public virtual IIS.ISS24.DetailArrayOfСписокФорм СписокФорм
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.СписокФорм Get start)

                // *** End programmer edit section *** (ВидПоддержки.СписокФорм Get start)
                if ((this.fСписокФорм == null))
                {
                    this.fСписокФорм = new IIS.ISS24.DetailArrayOfСписокФорм(this);
                }
                IIS.ISS24.DetailArrayOfСписокФорм result = this.fСписокФорм;
                // *** Start programmer edit section *** (ВидПоддержки.СписокФорм Get end)

                // *** End programmer edit section *** (ВидПоддержки.СписокФорм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.СписокФорм Set start)

                // *** End programmer edit section *** (ВидПоддержки.СписокФорм Set start)
                this.fСписокФорм = value;
                // *** Start programmer edit section *** (ВидПоддержки.СписокФорм Set end)

                // *** End programmer edit section *** (ВидПоддержки.СписокФорм Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидПоддержкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидПоддержкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидПоддержкиE", typeof(IIS.ISS24.ВидПоддержки));
                }
            }
            
            /// <summary>
            /// "ВидПоддержкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидПоддержкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидПоддержкиL", typeof(IIS.ISS24.ВидПоддержки));
                }
            }
        }
    }
}
