//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS24
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список форм.
    /// </summary>
    // *** Start programmer edit section *** (СписокФорм CustomAttributes)

    // *** End programmer edit section *** (СписокФорм CustomAttributes)
    [AutoAltered()]
    [Caption("Список форм")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокФормE", new string[] {
            "Наименование as \'Наименование\'",
            "Форма as \'Форма\'",
            "Форма.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Форма.Наименование"})]
    [MasterViewDefineAttribute("СписокФормE", "Форма", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СписокФорм : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.ISS24.Форма fФорма;
        
        private IIS.ISS24.ВидПоддержки fВидПоддержки;
        
        // *** Start programmer edit section *** (СписокФорм CustomMembers)

        // *** End programmer edit section *** (СписокФорм CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СписокФорм.Наименование CustomAttributes)

        // *** End programmer edit section *** (СписокФорм.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СписокФорм.Наименование Get start)

                // *** End programmer edit section *** (СписокФорм.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СписокФорм.Наименование Get end)

                // *** End programmer edit section *** (СписокФорм.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокФорм.Наименование Set start)

                // *** End programmer edit section *** (СписокФорм.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СписокФорм.Наименование Set end)

                // *** End programmer edit section *** (СписокФорм.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Список форм.
        /// </summary>
        // *** Start programmer edit section *** (СписокФорм.Форма CustomAttributes)

        // *** End programmer edit section *** (СписокФорм.Форма CustomAttributes)
        [NotNull()]
        public virtual IIS.ISS24.Форма Форма
        {
            get
            {
                // *** Start programmer edit section *** (СписокФорм.Форма Get start)

                // *** End programmer edit section *** (СписокФорм.Форма Get start)
                IIS.ISS24.Форма result = this.fФорма;
                // *** Start programmer edit section *** (СписокФорм.Форма Get end)

                // *** End programmer edit section *** (СписокФорм.Форма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокФорм.Форма Set start)

                // *** End programmer edit section *** (СписокФорм.Форма Set start)
                this.fФорма = value;
                // *** Start programmer edit section *** (СписокФорм.Форма Set end)

                // *** End programmer edit section *** (СписокФорм.Форма Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ISS24.ВидПоддержки.
        /// </summary>
        // *** Start programmer edit section *** (СписокФорм.ВидПоддержки CustomAttributes)

        // *** End programmer edit section *** (СписокФорм.ВидПоддержки CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.ISS24.ВидПоддержки ВидПоддержки
        {
            get
            {
                // *** Start programmer edit section *** (СписокФорм.ВидПоддержки Get start)

                // *** End programmer edit section *** (СписокФорм.ВидПоддержки Get start)
                IIS.ISS24.ВидПоддержки result = this.fВидПоддержки;
                // *** Start programmer edit section *** (СписокФорм.ВидПоддержки Get end)

                // *** End programmer edit section *** (СписокФорм.ВидПоддержки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокФорм.ВидПоддержки Set start)

                // *** End programmer edit section *** (СписокФорм.ВидПоддержки Set start)
                this.fВидПоддержки = value;
                // *** Start programmer edit section *** (СписокФорм.ВидПоддержки Set end)

                // *** End programmer edit section *** (СписокФорм.ВидПоддержки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокФормE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокФормE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокФормE", typeof(IIS.ISS24.СписокФорм));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СписокФорм.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСписокФорм CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСписокФорм CustomAttributes)
    public class DetailArrayOfСписокФорм : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ISS24.DetailArrayOfСписокФорм members)

        // *** End programmer edit section *** (IIS.ISS24.DetailArrayOfСписокФорм members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СписокФорм by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СписокФорм.
        /// </summary>
        public DetailArrayOfСписокФорм(IIS.ISS24.ВидПоддержки fВидПоддержки) : 
                base(typeof(СписокФорм), ((ICSSoft.STORMNET.DataObject)(fВидПоддержки)))
        {
        }
        
        public IIS.ISS24.СписокФорм this[int index]
        {
            get
            {
                return ((IIS.ISS24.СписокФорм)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ISS24.СписокФорм dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
