//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS24
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список условий.
    /// </summary>
    // *** Start programmer edit section *** (СписокУсловий CustomAttributes)

    // *** End programmer edit section *** (СписокУсловий CustomAttributes)
    [AutoAltered()]
    [Caption("Список условий")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокУсловийE", new string[] {
            "Наименование as \'Наименование\'",
            "Условие as \'Условие\'",
            "Условие.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Условие.Наименование"})]
    [MasterViewDefineAttribute("СписокУсловийE", "Условие", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СписокУсловий : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.ISS24.Условие fУсловие;
        
        private IIS.ISS24.ВидПоддержки fВидПоддержки;
        
        // *** Start programmer edit section *** (СписокУсловий CustomMembers)

        // *** End programmer edit section *** (СписокУсловий CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СписокУсловий.Наименование CustomAttributes)

        // *** End programmer edit section *** (СписокУсловий.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СписокУсловий.Наименование Get start)

                // *** End programmer edit section *** (СписокУсловий.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СписокУсловий.Наименование Get end)

                // *** End programmer edit section *** (СписокУсловий.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокУсловий.Наименование Set start)

                // *** End programmer edit section *** (СписокУсловий.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СписокУсловий.Наименование Set end)

                // *** End programmer edit section *** (СписокУсловий.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Список условий.
        /// </summary>
        // *** Start programmer edit section *** (СписокУсловий.Условие CustomAttributes)

        // *** End programmer edit section *** (СписокУсловий.Условие CustomAttributes)
        [NotNull()]
        public virtual IIS.ISS24.Условие Условие
        {
            get
            {
                // *** Start programmer edit section *** (СписокУсловий.Условие Get start)

                // *** End programmer edit section *** (СписокУсловий.Условие Get start)
                IIS.ISS24.Условие result = this.fУсловие;
                // *** Start programmer edit section *** (СписокУсловий.Условие Get end)

                // *** End programmer edit section *** (СписокУсловий.Условие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокУсловий.Условие Set start)

                // *** End programmer edit section *** (СписокУсловий.Условие Set start)
                this.fУсловие = value;
                // *** Start programmer edit section *** (СписокУсловий.Условие Set end)

                // *** End programmer edit section *** (СписокУсловий.Условие Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ISS24.ВидПоддержки.
        /// </summary>
        // *** Start programmer edit section *** (СписокУсловий.ВидПоддержки CustomAttributes)

        // *** End programmer edit section *** (СписокУсловий.ВидПоддержки CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.ISS24.ВидПоддержки ВидПоддержки
        {
            get
            {
                // *** Start programmer edit section *** (СписокУсловий.ВидПоддержки Get start)

                // *** End programmer edit section *** (СписокУсловий.ВидПоддержки Get start)
                IIS.ISS24.ВидПоддержки result = this.fВидПоддержки;
                // *** Start programmer edit section *** (СписокУсловий.ВидПоддержки Get end)

                // *** End programmer edit section *** (СписокУсловий.ВидПоддержки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокУсловий.ВидПоддержки Set start)

                // *** End programmer edit section *** (СписокУсловий.ВидПоддержки Set start)
                this.fВидПоддержки = value;
                // *** Start programmer edit section *** (СписокУсловий.ВидПоддержки Set end)

                // *** End programmer edit section *** (СписокУсловий.ВидПоддержки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокУсловийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокУсловийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокУсловийE", typeof(IIS.ISS24.СписокУсловий));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СписокУсловий.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСписокУсловий CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСписокУсловий CustomAttributes)
    public class DetailArrayOfСписокУсловий : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ISS24.DetailArrayOfСписокУсловий members)

        // *** End programmer edit section *** (IIS.ISS24.DetailArrayOfСписокУсловий members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СписокУсловий by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СписокУсловий.
        /// </summary>
        public DetailArrayOfСписокУсловий(IIS.ISS24.ВидПоддержки fВидПоддержки) : 
                base(typeof(СписокУсловий), ((ICSSoft.STORMNET.DataObject)(fВидПоддержки)))
        {
        }
        
        public IIS.ISS24.СписокУсловий this[int index]
        {
            get
            {
                return ((IIS.ISS24.СписокУсловий)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ISS24.СписокУсловий dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
