//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS24
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Условие.
    /// </summary>
    // *** Start programmer edit section *** (Условие CustomAttributes)

    // *** End programmer edit section *** (Условие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УсловиеE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("УсловиеL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Условие : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Условие CustomMembers)

        // *** End programmer edit section *** (Условие CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Условие.Наименование CustomAttributes)

        // *** End programmer edit section *** (Условие.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Условие.Наименование Get start)

                // *** End programmer edit section *** (Условие.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Условие.Наименование Get end)

                // *** End programmer edit section *** (Условие.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.Наименование Set start)

                // *** End programmer edit section *** (Условие.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Условие.Наименование Set end)

                // *** End programmer edit section *** (Условие.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УсловиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеE", typeof(IIS.ISS24.Условие));
                }
            }
            
            /// <summary>
            /// "УсловиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеL", typeof(IIS.ISS24.Условие));
                }
            }
        }
    }
}
